# Generated by Django 3.0.6 on 2020-05-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RIN', models.CharField(blank=True, max_length=100)),
                ('GSTN', models.CharField(blank=True, max_length=100)),
                ('INVOICEDATE', models.CharField(blank=True, max_length=100)),
                ('TOTALGST', models.CharField(blank=True, max_length=100)),
                ('MonthofPayment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
